# Generated by Django 4.0.3 on 2022-04-18 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0020_rename_address_receptionist_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptionist',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
